name: Branch Validation

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: read

jobs:
  validate:
    uses: JSL-Inc/new-golden-path-workflows/.github/workflows/branch-validation.yml@main
