name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  merge_group:

permissions:
  contents: read

jobs:
  quality:
    uses: JSL-Inc/new-golden-path-workflows/.github/workflows/ci.yml@condense-testing-branch

