name: Production Release

on:
  workflow_run:
    workflows: ["Branch Delivery Pipeline"]
    types: [completed]
    branches:
      - main
      - new-deploy-stuff-and-epreprod

permissions:
  actions: read
  contents: write
  pull-requests: read

jobs:
  release:
    uses: JSL-Inc/new-golden-path-workflows/.github/workflows/release.yml@main
